apiVersion: v1
kind: Service
metadata:
  name: example-nginx-service
  namespace: default
  labels:
    app: nginx
spec:
  selector:
    app: test
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000